In [1]:
import tensorflow as tf

In [2]:
import tfutil

In [3]:
const1 = tf.constant([1, 2, 3])

In [4]:
print(const1)

Tensor("Const:0", shape=(3,), dtype=int32)


In [5]:
print(tf.shape(const1))

Tensor("Shape:0", shape=(1,), dtype=int32)


In [6]:
tfutil.print_constant(const1)

[1 2 3]


In [7]:
ed_const1 = tf.expand_dims(const1, 0)

In [8]:
print(ed_const1)

Tensor("ExpandDims:0", shape=(1, 3), dtype=int32)


In [9]:
tfutil.print_operation_value(ed_const1)

[[1 2 3]]


In [10]:
print(tf.shape(ed_const1))

Tensor("Shape_1:0", shape=(2,), dtype=int32)


In [11]:
ed_const1 = tf.expand_dims(const1, 1)

In [12]:
print(ed_const1)

Tensor("ExpandDims_1:0", shape=(3, 1), dtype=int32)


In [13]:
tfutil.print_operation_value(ed_const1)

[[1]
 [2]
 [3]]


In [14]:
print(tf.shape(ed_const1))

Tensor("Shape_2:0", shape=(2,), dtype=int32)


In [15]:
ed_const1 = tf.expand_dims(const1, 1)

In [16]:
print(ed_const1)

Tensor("ExpandDims_2:0", shape=(3, 1), dtype=int32)


In [17]:
tfutil.print_operation_value(ed_const1)

[[1]
 [2]
 [3]]


In [18]:
print(tf.shape(ed_const1))

Tensor("Shape_3:0", shape=(2,), dtype=int32)


In [19]:
ed_const1 = tf.expand_dims(const1, -1)

In [20]:
print(ed_const1)

Tensor("ExpandDims_3:0", shape=(3, 1), dtype=int32)


In [21]:
tfutil.print_operation_value(ed_const1)

[[1]
 [2]
 [3]]


In [22]:
print(tf.shape(ed_const1))

Tensor("Shape_4:0", shape=(2,), dtype=int32)


In [23]:
const2 = tf.constant([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]], [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]])

In [24]:
print(const2)

Tensor("Const_1:0", shape=(2, 3, 5), dtype=int32)


In [25]:
print(tf.shape(const2))

Tensor("Shape_5:0", shape=(3,), dtype=int32)


In [26]:
tfutil.print_constant(const2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [27]:
ed_const2 = tf.expand_dims(const2, 0)

In [28]:
print(ed_const2)

Tensor("ExpandDims_4:0", shape=(1, 2, 3, 5), dtype=int32)


In [29]:
tfutil.print_operation_value(ed_const2)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]

  [[16 17 18 19 20]
   [21 22 23 24 25]
   [26 27 28 29 30]]]]


In [30]:
print(tf.shape(ed_const2))

Tensor("Shape_6:0", shape=(4,), dtype=int32)


In [31]:
ed_const2 = tf.expand_dims(const2, 1)

In [32]:
print(ed_const2)

Tensor("ExpandDims_5:0", shape=(2, 1, 3, 5), dtype=int32)


In [33]:
tfutil.print_operation_value(ed_const2)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]]


 [[[16 17 18 19 20]
   [21 22 23 24 25]
   [26 27 28 29 30]]]]


In [34]:
print(tf.shape(ed_const2))

Tensor("Shape_7:0", shape=(4,), dtype=int32)


In [35]:
ed_const2 = tf.expand_dims(const2, 2)

In [36]:
print(ed_const2)

Tensor("ExpandDims_6:0", shape=(2, 3, 1, 5), dtype=int32)


In [37]:
tfutil.print_operation_value(ed_const2)

[[[[ 1  2  3  4  5]]

  [[ 6  7  8  9 10]]

  [[11 12 13 14 15]]]


 [[[16 17 18 19 20]]

  [[21 22 23 24 25]]

  [[26 27 28 29 30]]]]


In [38]:
print(tf.shape(ed_const2))

Tensor("Shape_8:0", shape=(4,), dtype=int32)


In [39]:
ed_const2 = tf.expand_dims(const2, 3)

In [40]:
print(ed_const2)

Tensor("ExpandDims_7:0", shape=(2, 3, 5, 1), dtype=int32)


In [41]:
tfutil.print_operation_value(ed_const2)

[[[[ 1]
   [ 2]
   [ 3]
   [ 4]
   [ 5]]

  [[ 6]
   [ 7]
   [ 8]
   [ 9]
   [10]]

  [[11]
   [12]
   [13]
   [14]
   [15]]]


 [[[16]
   [17]
   [18]
   [19]
   [20]]

  [[21]
   [22]
   [23]
   [24]
   [25]]

  [[26]
   [27]
   [28]
   [29]
   [30]]]]


In [42]:
print(tf.shape(ed_const2))

Tensor("Shape_9:0", shape=(4,), dtype=int32)


In [43]:
ed_const2 = tf.expand_dims(const2, -1)

In [44]:
print(ed_const2)

Tensor("ExpandDims_8:0", shape=(2, 3, 5, 1), dtype=int32)


In [45]:
tfutil.print_operation_value(ed_const2)

[[[[ 1]
   [ 2]
   [ 3]
   [ 4]
   [ 5]]

  [[ 6]
   [ 7]
   [ 8]
   [ 9]
   [10]]

  [[11]
   [12]
   [13]
   [14]
   [15]]]


 [[[16]
   [17]
   [18]
   [19]
   [20]]

  [[21]
   [22]
   [23]
   [24]
   [25]]

  [[26]
   [27]
   [28]
   [29]
   [30]]]]


In [46]:
print(tf.shape(ed_const2))

Tensor("Shape_10:0", shape=(4,), dtype=int32)
