In [1]:
import tensorflow as tf

In [2]:
import tfutil

In [3]:
const1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(const1)

Tensor("Const:0", shape=(9,), dtype=int32)


In [5]:
tfutil.print_constant(const1)

[1 2 3 4 5 6 7 8 9]


In [6]:
rs_const1 = tf.reshape(const1, [3, 3])

In [7]:
print(rs_const1)

Tensor("Reshape:0", shape=(3, 3), dtype=int32)


In [8]:
tfutil.print_operation_value(rs_const1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
const2 = tf.constant([[[1, 1], [2, 2]], [[3, 3], [4, 4]]])

In [10]:
print(const2)

Tensor("Const_1:0", shape=(2, 2, 2), dtype=int32)


In [11]:
tfutil.print_constant(const2)

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]


In [12]:
rs_const2 = tf.reshape(const2, [2, 4])

In [13]:
print(rs_const2)

Tensor("Reshape_1:0", shape=(2, 4), dtype=int32)


In [14]:
tfutil.print_operation_value(rs_const2)

[[1 1 2 2]
 [3 3 4 4]]


In [15]:
const3 = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]], [[5, 5, 5], [6, 6, 6]]])

In [16]:
print(const3)

Tensor("Const_2:0", shape=(3, 2, 3), dtype=int32)


In [17]:
tfutil.print_constant(const3)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]


In [18]:
rs_const3 = tf.reshape(const3, [-1])

In [19]:
print(rs_const3)

Tensor("Reshape_2:0", shape=(18,), dtype=int32)


In [20]:
tfutil.print_operation_value(rs_const3)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


In [21]:
const4 = tf.constant([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [22]:
print(const4)

Tensor("Const_3:0", shape=(18,), dtype=int32)


In [23]:
tfutil.print_constant(const4)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]


In [24]:
rs_const4 = tf.reshape(const4, [2, -1])

In [25]:
print(rs_const4)

Tensor("Reshape_3:0", shape=(2, 9), dtype=int32)


In [26]:
tfutil.print_operation_value(rs_const4)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [27]:
const5 = tf.constant([[1, 1, 1, 2, 2, 2, 3, 3, 3], [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [28]:
print(const5)

Tensor("Const_4:0", shape=(2, 9), dtype=int32)


In [29]:
tfutil.print_constant(const5)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [30]:
rs_const5 = tf.reshape(const5, [2, -1, 3])

In [31]:
print(rs_const5)

Tensor("Reshape_4:0", shape=(2, 3, 3), dtype=int32)


In [32]:
tfutil.print_operation_value(rs_const5)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]


In [33]:
const6 = tf.constant([7])

In [34]:
print(const6)

Tensor("Const_5:0", shape=(1,), dtype=int32)


In [35]:
tfutil.print_constant(const6)

[7]


In [36]:
rs_const6 = tf.reshape(const6, [])

In [37]:
print(rs_const6)

Tensor("Reshape_5:0", shape=(), dtype=int32)


In [38]:
tfutil.print_operation_value(rs_const6)

7
