In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [1]
const1 = tf.constant(np.array(x))
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(1,), dtype=int64)
Tensor("Shape:0", shape=(1,), dtype=int32)
[1]


In [3]:
sn_const1 = tf.shape_n([const1])
print(sn_const1)
tfutil.print_operation_value(sn_const1)

[<tf.Tensor 'ShapeN:0' shape=(1,) dtype=int32>]
[array([1], dtype=int32)]


In [4]:
x = [1, 2]
const2 = tf.constant(np.array(x))
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(2,), dtype=int64)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[1 2]


In [5]:
sn_const2 = tf.shape_n([const2])
print(sn_const2)
tfutil.print_operation_value(sn_const2)

[<tf.Tensor 'ShapeN_1:0' shape=(1,) dtype=int32>]
[array([2], dtype=int32)]


In [6]:
x = [[1, 2], [3, 4]]
const3 = tf.constant(np.array(x))
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(2, 2), dtype=int64)
Tensor("Shape_2:0", shape=(2,), dtype=int32)
[[1 2]
 [3 4]]


In [7]:
sn_const3 = tf.shape_n([const3])
print(sn_const3)
tfutil.print_operation_value(sn_const3)

[<tf.Tensor 'ShapeN_2:0' shape=(2,) dtype=int32>]
[array([2, 2], dtype=int32)]


In [8]:
x = [[1, 2], [3, 4], [5, 6]]
const4 = tf.constant(np.array(x))
print(const4)
print(tf.shape(const4))
tfutil.print_constant(const4)

Tensor("Const_3:0", shape=(3, 2), dtype=int64)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[1 2]
 [3 4]
 [5 6]]


In [9]:
sn_const4 = tf.shape_n([const4])
print(sn_const4)
tfutil.print_operation_value(sn_const4)

[<tf.Tensor 'ShapeN_3:0' shape=(2,) dtype=int32>]
[array([3, 2], dtype=int32)]


In [10]:
x = [[[1], [2]], [[3], [4]]]
const5 = tf.constant(np.array(x))
print(const5)
print(tf.shape(const5))
tfutil.print_constant(const5)

Tensor("Const_4:0", shape=(2, 2, 1), dtype=int64)
Tensor("Shape_4:0", shape=(3,), dtype=int32)
[[[1]
  [2]]

 [[3]
  [4]]]


In [11]:
sn_const5 = tf.shape_n([const5])
print(sn_const5)
tfutil.print_operation_value(sn_const5)

[<tf.Tensor 'ShapeN_4:0' shape=(3,) dtype=int32>]
[array([2, 2, 1], dtype=int32)]


In [12]:
x = [[[1], [2]], [[3], [4]], [[5], [6]]]
const6 = tf.constant(np.array(x))
print(const6)
print(tf.shape(const6))
tfutil.print_constant(const6)

Tensor("Const_5:0", shape=(3, 2, 1), dtype=int64)
Tensor("Shape_5:0", shape=(3,), dtype=int32)
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [13]:
sn_const6 = tf.shape_n([const6])
print(sn_const6)
tfutil.print_operation_value(sn_const6)

[<tf.Tensor 'ShapeN_5:0' shape=(3,) dtype=int32>]
[array([3, 2, 1], dtype=int32)]


In [14]:
sn_const6 = tf.shape_n([[const6]])
print(sn_const6)
tfutil.print_operation_value(sn_const6)

[<tf.Tensor 'ShapeN_6:0' shape=(4,) dtype=int32>]
[array([1, 3, 2, 1], dtype=int32)]
