In [1]:
import tensorflow as tf

In [2]:
import tfutil

In [3]:
const1 = tf.constant(1)

In [4]:
tfutil.print_constant(const1)

1


In [5]:
print(const1)

Tensor("Const:0", shape=(), dtype=int32)


In [6]:
tfutil.print_operation_value(tf.size(const1))

1


In [7]:
const2 = tf.constant([1, 2])

In [8]:
tfutil.print_constant(const2)

[1 2]


In [9]:
print(const2)

Tensor("Const_1:0", shape=(2,), dtype=int32)


In [10]:
tfutil.print_operation_value(tf.size(const2))

2


In [11]:
const3 = tf.constant([[1, 2], [3, 4]])

In [12]:
tfutil.print_constant(const3)

[[1 2]
 [3 4]]


In [13]:
print(const3)

Tensor("Const_2:0", shape=(2, 2), dtype=int32)


In [14]:
tfutil.print_operation_value(tf.size(const3))

4


In [15]:
const4 = tf.constant([[1, 2], [3, 4], [5, 6]])

In [16]:
tfutil.print_constant(const4)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
print(const4)

Tensor("Const_3:0", shape=(3, 2), dtype=int32)


In [18]:
tfutil.print_operation_value(tf.size(const4))

6


In [19]:
const5 = tf.constant([[[1], [2]], [[3], [4]]])

In [20]:
tfutil.print_constant(const5)

[[[1]
  [2]]

 [[3]
  [4]]]


In [21]:
print(const5)

Tensor("Const_4:0", shape=(2, 2, 1), dtype=int32)


In [22]:
tfutil.print_operation_value(tf.size(const5))

4


In [23]:
const6 = tf.constant([[[1], [2]], [[3], [4]], [[5], [6]]])

In [24]:
tfutil.print_constant(const6) 

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [25]:
print(const6)

Tensor("Const_5:0", shape=(3, 2, 1), dtype=int32)


In [26]:
tfutil.print_operation_value(tf.size(const6))

6
