In [1]:
import tensorflow as tf

In [2]:
import tfutil

In [3]:
# [1, 2, 1, 3, 1, 1]

In [4]:
const1 = tf.constant([[ [[ [[1]], [[2]], [[3]] ]], [[ [[4]], [[5]], [[6]] ]] ]])

In [5]:
print(const1)

Tensor("Const:0", shape=(1, 2, 1, 3, 1, 1), dtype=int32)


In [6]:
print(tf.shape(const1))

Tensor("Shape:0", shape=(6,), dtype=int32)


In [7]:
tfutil.print_constant(const1)

[[[[[[1]]

    [[2]]

    [[3]]]]



  [[[[4]]

    [[5]]

    [[6]]]]]]


In [8]:
sq_const1 = tf.squeeze(const1)

In [9]:
print(sq_const1)

Tensor("Squeeze:0", shape=(2, 3), dtype=int32)


In [10]:
print(tf.shape(sq_const1))

Tensor("Shape_1:0", shape=(2,), dtype=int32)


In [11]:
tfutil.print_operation_value(sq_const1)

[[1 2 3]
 [4 5 6]]


In [12]:
# [1, 2, 1, 3, 1, 1]

In [13]:
const2 = tf.constant([[ [[ [[1]], [[2]], [[3]] ]], [[ [[4]], [[5]], [[6]] ]] ]])

In [14]:
print(const2)

Tensor("Const_1:0", shape=(1, 2, 1, 3, 1, 1), dtype=int32)


In [15]:
print(tf.shape(const2))

Tensor("Shape_2:0", shape=(6,), dtype=int32)


In [16]:
tfutil.print_constant(const2)

[[[[[[1]]

    [[2]]

    [[3]]]]



  [[[[4]]

    [[5]]

    [[6]]]]]]


In [17]:
sq_const2 = tf.squeeze(const2, [0])

In [18]:
print(sq_const2)

Tensor("Squeeze_1:0", shape=(2, 1, 3, 1, 1), dtype=int32)


In [19]:
print(tf.shape(sq_const2))

Tensor("Shape_3:0", shape=(5,), dtype=int32)


In [20]:
tfutil.print_operation_value(sq_const2)

[[[[[1]]

   [[2]]

   [[3]]]]



 [[[[4]]

   [[5]]

   [[6]]]]]


In [21]:
sq_const2 = tf.squeeze(const2, [2])

In [22]:
print(sq_const2)

Tensor("Squeeze_2:0", shape=(1, 2, 3, 1, 1), dtype=int32)


In [23]:
print(tf.shape(sq_const2))

Tensor("Shape_4:0", shape=(5,), dtype=int32)


In [24]:
tfutil.print_operation_value(sq_const2)

[[[[[1]]

   [[2]]

   [[3]]]


  [[[4]]

   [[5]]

   [[6]]]]]


In [25]:
sq_const2 = tf.squeeze(const2, [0, 2])

In [26]:
print(sq_const2)

Tensor("Squeeze_3:0", shape=(2, 3, 1, 1), dtype=int32)


In [27]:
print(tf.shape(sq_const2))

Tensor("Shape_5:0", shape=(4,), dtype=int32)


In [28]:
tfutil.print_operation_value(sq_const2)

[[[[1]]

  [[2]]

  [[3]]]


 [[[4]]

  [[5]]

  [[6]]]]


In [29]:
sq_const2 = tf.squeeze(const2, [2, 4])

In [30]:
print(sq_const2)

Tensor("Squeeze_4:0", shape=(1, 2, 3, 1), dtype=int32)


In [31]:
print(tf.shape(sq_const2))

Tensor("Shape_6:0", shape=(4,), dtype=int32)


In [32]:
tfutil.print_operation_value(sq_const2)

[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]]]


In [33]:
sq_const2 = tf.squeeze(const2, [0, 2, 4])

In [34]:
print(sq_const2)

Tensor("Squeeze_5:0", shape=(2, 3, 1), dtype=int32)


In [35]:
print(tf.shape(sq_const2))

Tensor("Shape_7:0", shape=(3,), dtype=int32)


In [36]:
tfutil.print_operation_value(sq_const2)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [37]:
sq_const2 = tf.squeeze(const2, [0, 2, 4, 5])

In [38]:
print(sq_const2)

Tensor("Squeeze_6:0", shape=(2, 3), dtype=int32)


In [39]:
print(tf.shape(sq_const2))

Tensor("Shape_8:0", shape=(2,), dtype=int32)


In [40]:
tfutil.print_operation_value(sq_const2)

[[1 2 3]
 [4 5 6]]
