In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [[[[1]]], [[[2]]], [[[3]]], [[[4]]]]

const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(4, 1, 1, 1), dtype=int32)
Tensor("Shape:0", shape=(4,), dtype=int32)
[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]]


In [3]:
# crops = [[crop_top, crop_bottom], [crop_left, crop_right]]
# [batch, height, width, depth]
# height = height_pad - crop_top - crop_bottom
# width = width_pad - crop_left - crop_right

corps = [[0, 0],[0, 1]]
blocksize = 1
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND:0", shape=(4, 1, 0, 1), dtype=int32)
Tensor("Shape_1:0", shape=(4,), dtype=int32)
[]


In [4]:
corps = [[0, 0],[0, 1]]
blocksize = 1
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_1:0", shape=(4, 1, 0, 1), dtype=int32)
Tensor("Shape_2:0", shape=(4,), dtype=int32)
[]


In [5]:
corps = [[0, 1],[0, 0]]
blocksize = 1
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_2:0", shape=(4, 0, 1, 1), dtype=int32)
Tensor("Shape_3:0", shape=(4,), dtype=int32)
[]


In [6]:
corps = [[1, 0],[0, 0]]
blocksize = 1
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_3:0", shape=(4, 0, 1, 1), dtype=int32)
Tensor("Shape_4:0", shape=(4,), dtype=int32)
[]


In [7]:
corps = [[0, 0],[0, 0]]
blocksize = 2
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_4:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_5:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [8]:
corps = [[0, 0],[1, 1]]
blocksize = 2
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_5:0", shape=(1, 2, 0, 1), dtype=int32)
Tensor("Shape_6:0", shape=(4,), dtype=int32)
[]


In [9]:
corps = [[1, 1],[0, 0]]
blocksize = 2
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_6:0", shape=(1, 0, 2, 1), dtype=int32)
Tensor("Shape_7:0", shape=(4,), dtype=int32)
[]


In [10]:
corps = [[1, 1],[1, 1]]
blocksize = 2
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_7:0", shape=(1, 0, 0, 1), dtype=int32)
Tensor("Shape_8:0", shape=(4,), dtype=int32)
[]


In [11]:
x = [[[[ 1,  2,  3]]],
 [[[ 4,  5,  6]]],
 [[[ 7,  8,  9]]],
 [[[10, 11, 12]]]]
const2 = tf.constant(np.array(x), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(4, 1, 1, 3), dtype=int32)
Tensor("Shape_9:0", shape=(4,), dtype=int32)
[[[[ 1  2  3]]]


 [[[ 4  5  6]]]


 [[[ 7  8  9]]]


 [[[10 11 12]]]]


In [12]:
corps = [[0, 0],[0, 0]]
blocksize = 2
bts_const1 = tf.batch_to_space(const1, corps, blocksize)
print(bts_const1)
print(tf.shape(bts_const1))
tfutil.print_operation_value(bts_const1)

Tensor("BatchToSpaceND_8:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_10:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [13]:
x = [[[[1], [3]], [[9], [11]]],
     [[[2], [4]], [[10], [12]]],
     [[[5], [7]], [[13], [15]]],
     [[[6], [8]], [[14], [16]]]]
const3 = tf.constant(np.array(x), dtype=tf.int32)
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(4, 2, 2, 1), dtype=int32)
Tensor("Shape_11:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 3]]

  [[ 9]
   [11]]]


 [[[ 2]
   [ 4]]

  [[10]
   [12]]]


 [[[ 5]
   [ 7]]

  [[13]
   [15]]]


 [[[ 6]
   [ 8]]

  [[14]
   [16]]]]


In [14]:
corps = [[0, 0],[0, 0]]
blocksize = 2
bts_const3 = tf.batch_to_space(const3, corps, blocksize)
print(bts_const3)
print(tf.shape(bts_const3))
tfutil.print_operation_value(bts_const3)

Tensor("BatchToSpaceND_9:0", shape=(1, 4, 4, 1), dtype=int32)
Tensor("Shape_12:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [11]
   [12]]

  [[13]
   [14]
   [15]
   [16]]]]


In [15]:
x = [[[[1], [3]]], [[[9], [11]]], [[[2], [4]]], [[[10], [12]]],
     [[[5], [7]]], [[[13], [15]]], [[[6], [8]]], [[[14], [16]]]]
const4 = tf.constant(np.array(x), dtype=tf.int32)
print(const4)
print(tf.shape(const4))
tfutil.print_constant(const4)

Tensor("Const_3:0", shape=(8, 1, 2, 1), dtype=int32)
Tensor("Shape_13:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 3]]]


 [[[ 9]
   [11]]]


 [[[ 2]
   [ 4]]]


 [[[10]
   [12]]]


 [[[ 5]
   [ 7]]]


 [[[13]
   [15]]]


 [[[ 6]
   [ 8]]]


 [[[14]
   [16]]]]


In [16]:
corps = [[0, 0],[0, 0]]
blocksize = 2
bts_const4 = tf.batch_to_space(const4, corps, blocksize)
print(bts_const4)
print(tf.shape(bts_const4))
tfutil.print_operation_value(bts_const4)

Tensor("BatchToSpaceND_10:0", shape=(2, 2, 4, 1), dtype=int32)
Tensor("Shape_14:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]]]


 [[[ 9]
   [10]
   [11]
   [12]]

  [[13]
   [14]
   [15]
   [16]]]]
