In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [0, 1, 2, 3]
const1 = tf.constant(np.array(x))
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(4,), dtype=int64)
Tensor("Shape:0", shape=(1,), dtype=int32)
[0 1 2 3]


In [3]:
mask = np.array([True, False, True, False])
bm_const1 = tf.boolean_mask(const1, mask)
print(bm_const1)
print(tf.shape(bm_const1))
tfutil.print_operation_value(bm_const1)

Tensor("boolean_mask/Gather:0", shape=(?,), dtype=int64)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[0 2]


In [4]:
x = [[1, 2], [3, 4], [5, 6]]
const2 = tf.constant(np.array(x)) 
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(3, 2), dtype=int64)
Tensor("Shape_2:0", shape=(2,), dtype=int32)
[[1 2]
 [3 4]
 [5 6]]


In [5]:
mask = np.array([True, False, True])
bm_const2 = tf.boolean_mask(const2, mask)
print(bm_const2)
print(tf.shape(bm_const2))
tfutil.print_operation_value(bm_const2)

Tensor("boolean_mask_1/Gather:0", shape=(?, 2), dtype=int64)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[1 2]
 [5 6]]
