In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
# [[1, 2, 3], [4, 5, 6]]
const1 = tf.constant(np.array([[1, 2, 3], [4, 5, 6]]), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(2, 3), dtype=int32)
Tensor("Shape:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]]


In [3]:
# [[7, 8, 9], [10, 11, 12]]
const2 = tf.constant(np.array([[7, 8, 9], [10, 11, 12]]), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(2, 3), dtype=int32)
Tensor("Shape_1:0", shape=(2,), dtype=int32)
[[ 7  8  9]
 [10 11 12]]


In [4]:
cc_const1 = tf.concat([const1, const2], 0)
print(cc_const1)
print(tf.shape(cc_const1))
tfutil.print_operation_value(cc_const1)

Tensor("concat:0", shape=(4, 3), dtype=int32)
Tensor("Shape_2:0", shape=(2,), dtype=int32)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
cc_const1 = tf.concat([const1, const2], 1)
print(cc_const1)
print(tf.shape(cc_const1))
tfutil.print_operation_value(cc_const1)

Tensor("concat_1:0", shape=(2, 6), dtype=int32)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
