In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [[[[1, 2, 3, 4]]]]
const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(1, 1, 1, 4), dtype=int32)
Tensor("Shape:0", shape=(4,), dtype=int32)
[[[[1 2 3 4]]]]


In [3]:
blocksize = 2
dts_const1 = tf.depth_to_space(const1, blocksize)
print(dts_const1)
print(tf.shape(dts_const1))
tfutil.print_operation_value(dts_const1)

Tensor("DepthToSpace:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_1:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [4]:
x = [[[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]]]
const2 = tf.constant(np.array(x), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(1, 1, 1, 12), dtype=int32)
Tensor("Shape_2:0", shape=(4,), dtype=int32)
[[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]]


In [5]:
blocksize = 2
dts_const2 = tf.depth_to_space(const2, blocksize)
print(dts_const2)
print(tf.shape(dts_const2))
tfutil.print_operation_value(dts_const2)

Tensor("DepthToSpace_1:0", shape=(1, 2, 2, 3), dtype=int32)
Tensor("Shape_3:0", shape=(4,), dtype=int32)
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [6]:
x =  [[[[1, 2, 3, 4],
       [5, 6, 7, 8]],
      [[9, 10, 11, 12],
       [13, 14, 15, 16]]]]
const3 = tf.constant(np.array(x), dtype=tf.int32)
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(1, 2, 2, 4), dtype=int32)
Tensor("Shape_4:0", shape=(4,), dtype=int32)
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]]]


In [7]:
blocksize = 2
dts_const3 = tf.depth_to_space(const3, blocksize)
print(dts_const3)
print(tf.shape(dts_const3))
tfutil.print_operation_value(dts_const3)

Tensor("DepthToSpace_2:0", shape=(1, 4, 4, 1), dtype=int32)
Tensor("Shape_5:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 2]
   [ 5]
   [ 6]]

  [[ 3]
   [ 4]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [13]
   [14]]

  [[11]
   [12]
   [15]
   [16]]]]
