In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
# outputs[i].shape = [sum(partitions == i)] + data.shape[partitions.ndim:]
# outputs[i] = pack([data[js, ...] for js if partitions[js] == i])

x = [10, 20]
const1 = tf.constant(np.array(x))
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(2,), dtype=int64)
Tensor("Shape:0", shape=(1,), dtype=int32)
[10 20]


In [3]:
# Scalar partitions.
partitions = 1 
num_partitions = 2 
dyp_const1 = tf.dynamic_partition(const1, partitions, num_partitions)
print(dyp_const1[0])
print(tf.shape(dyp_const1[0]))
tfutil.print_operation_value(dyp_const1[0])

Tensor("DynamicPartition:0", shape=(?, 2), dtype=int64)
Tensor("Shape_1:0", shape=(2,), dtype=int32)
[]


In [4]:
print(dyp_const1[1])
print(tf.shape(dyp_const1[1]))
tfutil.print_operation_value(dyp_const1[1])

Tensor("DynamicPartition:1", shape=(?, 2), dtype=int64)
Tensor("Shape_2:0", shape=(2,), dtype=int32)
[[10 20]]


In [5]:
print(dyp_const1)
print(tf.shape(dyp_const1))
tfutil.print_operation_value(dyp_const1)

[<tf.Tensor 'DynamicPartition:0' shape=(?, 2) dtype=int64>, <tf.Tensor 'DynamicPartition:1' shape=(?, 2) dtype=int64>]
Tensor("Shape_3:0", shape=(3,), dtype=int32)
[array([], shape=(0, 2), dtype=int64), array([[10, 20]])]


In [6]:
x = [10, 20, 30, 40, 50]
const2 = tf.constant(np.array(x))
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(5,), dtype=int64)
Tensor("Shape_4:0", shape=(1,), dtype=int32)
[10 20 30 40 50]


In [7]:
# Vector partitions.
partitions = [0, 0, 1, 1, 0]
num_partitions = 2
dyp_const2 = tf.dynamic_partition(const2, partitions, num_partitions)
print(dyp_const2[0])
print(tf.shape(dyp_const2[0]))
tfutil.print_operation_value(dyp_const2[0])

Tensor("DynamicPartition_1:0", shape=(?,), dtype=int64)
Tensor("Shape_5:0", shape=(1,), dtype=int32)
[10 20 50]


In [8]:
print(dyp_const2[1])
print(tf.shape(dyp_const2[1]))
tfutil.print_operation_value(dyp_const2[1])

Tensor("DynamicPartition_1:1", shape=(?,), dtype=int64)
Tensor("Shape_6:0", shape=(1,), dtype=int32)
[30 40]


In [9]:
print(dyp_const2)
print(tf.shape(dyp_const2))
tfutil.print_operation_value(dyp_const2)

[<tf.Tensor 'DynamicPartition_1:0' shape=(?,) dtype=int64>, <tf.Tensor 'DynamicPartition_1:1' shape=(?,) dtype=int64>]
Tensor("Shape_7:0", shape=(2,), dtype=int32)
[array([10, 20, 50]), array([30, 40])]
