In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
n = 10
# images is a 1 x 10 x 10 x 1 array that contains the numbers 1 through 100 in order
images = [[[[x * n + y + 1] for y in range(n)] for x in range(n)]]

const1 = tf.constant(np.array(images), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(1, 10, 10, 1), dtype=int32)
Tensor("Shape:0", shape=(4,), dtype=int32)
[[[[  1]
   [  2]
   [  3]
   [  4]
   [  5]
   [  6]
   [  7]
   [  8]
   [  9]
   [ 10]]

  [[ 11]
   [ 12]
   [ 13]
   [ 14]
   [ 15]
   [ 16]
   [ 17]
   [ 18]
   [ 19]
   [ 20]]

  [[ 21]
   [ 22]
   [ 23]
   [ 24]
   [ 25]
   [ 26]
   [ 27]
   [ 28]
   [ 29]
   [ 30]]

  [[ 31]
   [ 32]
   [ 33]
   [ 34]
   [ 35]
   [ 36]
   [ 37]
   [ 38]
   [ 39]
   [ 40]]

  [[ 41]
   [ 42]
   [ 43]
   [ 44]
   [ 45]
   [ 46]
   [ 47]
   [ 48]
   [ 49]
   [ 50]]

  [[ 51]
   [ 52]
   [ 53]
   [ 54]
   [ 55]
   [ 56]
   [ 57]
   [ 58]
   [ 59]
   [ 60]]

  [[ 61]
   [ 62]
   [ 63]
   [ 64]
   [ 65]
   [ 66]
   [ 67]
   [ 68]
   [ 69]
   [ 70]]

  [[ 71]
   [ 72]
   [ 73]
   [ 74]
   [ 75]
   [ 76]
   [ 77]
   [ 78]
   [ 79]
   [ 80]]

  [[ 81]
   [ 82]
   [ 83]
   [ 84]
   [ 85]
   [ 86]
   [ 87]
   [ 88]
   [ 89]
   [ 90]]

  [[ 91]
   [ 92]
   [ 93]
   [ 94]
   [ 95]
   [ 96]
   [ 97]
   [ 98]
   [

In [3]:
# Ksizes Test
# output_depth = ksize_rows * ksize_cols * depth = (1 x 1 x 1 ) = 1
# ksizes: raws: [1] col: [1]
ksizes = [1, 1, 1, 1]
strides = [1, 3, 3, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches:0", shape=(1, 4, 4, 1), dtype=int32)
Tensor("Shape_1:0", shape=(4,), dtype=int32)
[[[[  1]
   [  4]
   [  7]
   [ 10]]

  [[ 31]
   [ 34]
   [ 37]
   [ 40]]

  [[ 61]
   [ 64]
   [ 67]
   [ 70]]

  [[ 91]
   [ 94]
   [ 97]
   [100]]]]


In [4]:
# Ksizes Test
# output_depth = ksize_rows * ksize_cols * depth = (1 x 2 x 1 ) = 2
# ksizes: raws: [1, 2]  col: [1, 2]
ksizes = [1, 1, 2, 1]
strides = [1, 3, 3, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_1:0", shape=(1, 4, 3, 2), dtype=int32)
Tensor("Shape_2:0", shape=(4,), dtype=int32)
[[[[ 1  2]
   [ 4  5]
   [ 7  8]]

  [[31 32]
   [34 35]
   [37 38]]

  [[61 62]
   [64 65]
   [67 68]]

  [[91 92]
   [94 95]
   [97 98]]]]


In [5]:
# Ksizes Test
# output_depth = ksize_rows * ksize_cols * depth = (1 x 3 x 1 ) = 3
# ksizes: raws: [1, 2, 3]   col: [1, 2, 3]
ksizes = [1, 1, 3, 1]
strides = [1, 3, 3, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_2:0", shape=(1, 4, 3, 3), dtype=int32)
Tensor("Shape_3:0", shape=(4,), dtype=int32)
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[31 32 33]
   [34 35 36]
   [37 38 39]]

  [[61 62 63]
   [64 65 66]
   [67 68 69]]

  [[91 92 93]
   [94 95 96]
   [97 98 99]]]]


In [6]:
# Ksizes Test
# output_depth = ksize_rows * ksize_cols * depth = (2 x 3 x 1 ) = 6 -> [ 1  2  3 11 12 13] ..
# ksizes: raws: [1  2  3 ]   col: [1  2  3 11 12 13]
ksizes = [1, 2, 3, 1]
strides = [1, 3, 3, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_3:0", shape=(1, 3, 3, 6), dtype=int32)
Tensor("Shape_4:0", shape=(4,), dtype=int32)
[[[[ 1  2  3 11 12 13]
   [ 4  5  6 14 15 16]
   [ 7  8  9 17 18 19]]

  [[31 32 33 41 42 43]
   [34 35 36 44 45 46]
   [37 38 39 47 48 49]]

  [[61 62 63 71 72 73]
   [64 65 66 74 75 76]
   [67 68 69 77 78 79]]]]


In [7]:
# Ksizes Test
# output_depth = ksize_rows * ksize_cols * depth = (3 x 3 x 1 ) = 9 -> [ 1 2 3 11 12 13 21 22 23] ..
# ksizes: raws: [1  2  3 ]   col: [1  2  3 11 12 13 21 22 23]
ksizes = [1, 3, 3, 1]
strides = [1, 3, 3, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_4:0", shape=(1, 3, 3, 9), dtype=int32)
Tensor("Shape_5:0", shape=(4,), dtype=int32)
[[[[ 1  2  3 11 12 13 21 22 23]
   [ 4  5  6 14 15 16 24 25 26]
   [ 7  8  9 17 18 19 27 28 29]]

  [[31 32 33 41 42 43 51 52 53]
   [34 35 36 44 45 46 54 55 56]
   [37 38 39 47 48 49 57 58 59]]

  [[61 62 63 71 72 73 81 82 83]
   [64 65 66 74 75 76 84 85 86]
   [67 68 69 77 78 79 87 88 89]]]]


In [8]:
# strides Test
# output_depth = ksize_rows * ksize_cols * depth = (3 x 3 x 1 ) = 9 -> [ 1 2 3 11 12 13 21 22 23] ..
# strides: raws: [1, 4, 7]   col: [1, 31, 61]
ksizes = [1, 3, 3, 1]
strides = [1, 3, 3, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_5:0", shape=(1, 3, 3, 9), dtype=int32)
Tensor("Shape_6:0", shape=(4,), dtype=int32)
[[[[ 1  2  3 11 12 13 21 22 23]
   [ 4  5  6 14 15 16 24 25 26]
   [ 7  8  9 17 18 19 27 28 29]]

  [[31 32 33 41 42 43 51 52 53]
   [34 35 36 44 45 46 54 55 56]
   [37 38 39 47 48 49 57 58 59]]

  [[61 62 63 71 72 73 81 82 83]
   [64 65 66 74 75 76 84 85 86]
   [67 68 69 77 78 79 87 88 89]]]]


In [9]:
# strides Test
# output_depth = ksize_rows * ksize_cols * depth = (3 x 3 x 1 ) = 9 -> [ 1 2 3 11 12 13 21 22 23] ..
# strides: raws: [1, 4, 7]   col: [1, 21, 41, 61]
ksizes = [1, 3, 3, 1]
strides = [1, 2, 3, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_6:0", shape=(1, 4, 3, 9), dtype=int32)
Tensor("Shape_7:0", shape=(4,), dtype=int32)
[[[[ 1  2  3 11 12 13 21 22 23]
   [ 4  5  6 14 15 16 24 25 26]
   [ 7  8  9 17 18 19 27 28 29]]

  [[21 22 23 31 32 33 41 42 43]
   [24 25 26 34 35 36 44 45 46]
   [27 28 29 37 38 39 47 48 49]]

  [[41 42 43 51 52 53 61 62 63]
   [44 45 46 54 55 56 64 65 66]
   [47 48 49 57 58 59 67 68 69]]

  [[61 62 63 71 72 73 81 82 83]
   [64 65 66 74 75 76 84 85 86]
   [67 68 69 77 78 79 87 88 89]]]]


In [10]:
# strides Test
# output_depth = ksize_rows * ksize_cols * depth = (3 x 3 x 1 ) = 9 -> [ 1 2 3 11 12 13 21 22 23] ..
# strides: raws: [1, 3, 5, 7]   col: [1, 31, 61]
ksizes = [1, 3, 3, 1]
strides = [1, 3, 2, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_7:0", shape=(1, 3, 4, 9), dtype=int32)
Tensor("Shape_8:0", shape=(4,), dtype=int32)
[[[[ 1  2  3 11 12 13 21 22 23]
   [ 3  4  5 13 14 15 23 24 25]
   [ 5  6  7 15 16 17 25 26 27]
   [ 7  8  9 17 18 19 27 28 29]]

  [[31 32 33 41 42 43 51 52 53]
   [33 34 35 43 44 45 53 54 55]
   [35 36 37 45 46 47 55 56 57]
   [37 38 39 47 48 49 57 58 59]]

  [[61 62 63 71 72 73 81 82 83]
   [63 64 65 73 74 75 83 84 85]
   [65 66 67 75 76 77 85 86 87]
   [67 68 69 77 78 79 87 88 89]]]]


In [11]:
# We generate four outputs as follows:
# 1. 3x3 patches with stride length 5
ksizes = [1, 3, 3, 1]
strides = [1, 5, 5, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_8:0", shape=(1, 2, 2, 9), dtype=int32)
Tensor("Shape_9:0", shape=(4,), dtype=int32)
[[[[ 1  2  3 11 12 13 21 22 23]
   [ 6  7  8 16 17 18 26 27 28]]

  [[51 52 53 61 62 63 71 72 73]
   [56 57 58 66 67 68 76 77 78]]]]


In [12]:
# 2. Same as above, but the rate is increased to 2
ksizes = [1, 3, 3, 1]
strides = [1, 5, 5, 1]
rates = [1, 2, 2, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_9:0", shape=(1, 2, 2, 9), dtype=int32)
Tensor("Shape_10:0", shape=(4,), dtype=int32)
[[[[  1   3   5  21  23  25  41  43  45]
   [  6   8  10  26  28  30  46  48  50]]

  [[ 51  53  55  71  73  75  91  93  95]
   [ 56  58  60  76  78  80  96  98 100]]]]


In [13]:
# 3. 4x4 patches with stride length 7; only one patch should be generated
ksizes = [1, 4, 4, 1]
strides = [1, 7, 7, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='VALID')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_10:0", shape=(1, 1, 1, 16), dtype=int32)
Tensor("Shape_11:0", shape=(4,), dtype=int32)
[[[[ 1  2  3  4 11 12 13 14 21 22 23 24 31 32 33 34]]]]


In [14]:
# 4. Same as above, but with padding set to 'SAME'
ksizes = [1, 4, 4, 1]
strides = [1, 7, 7, 1]
rates = [1, 1, 1, 1]
exi_const1 = tf.extract_image_patches(const1, ksizes, strides, rates, padding='SAME')
print(exi_const1)
print(tf.shape(exi_const1))
tfutil.print_operation_value(exi_const1)

Tensor("ExtractImagePatches_11:0", shape=(1, 2, 2, 16), dtype=int32)
Tensor("Shape_12:0", shape=(4,), dtype=int32)
[[[[  1   2   3   4  11  12  13  14  21  22  23  24  31  32  33  34]
   [  8   9  10   0  18  19  20   0  28  29  30   0  38  39  40   0]]

  [[ 71  72  73  74  81  82  83  84  91  92  93  94   0   0   0   0]
   [ 78  79  80   0  88  89  90   0  98  99 100   0   0   0   0   0]]]]
