In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [[1, 2, 3],
     [4, 5, 6],  
     [7, 8, 9]] 
const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(3, 3), dtype=int32)
Tensor("Shape:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
idx_const2 = tf.constant([1, 0, 2])
print(idx_const2)
print(tf.shape(idx_const2))
tfutil.print_constant(idx_const2)

Tensor("Const_1:0", shape=(3,), dtype=int32)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[1 0 2]


In [4]:
idx_flattened = tf.range(0, const1.shape[0]) * const1.shape[1] + idx_const2
print(idx_flattened)
print(tf.shape(idx_flattened))
tfutil.print_constant(idx_flattened)

Tensor("add:0", shape=(3,), dtype=int32)
Tensor("Shape_2:0", shape=(1,), dtype=int32)
[1 3 8]


In [5]:
# partial code 1
print(const1.shape[0])
tmp1 = tf.range(0, const1.shape[0])
print(tmp1)
print(tf.shape(tmp1))
tfutil.print_constant(tmp1)

3
Tensor("range_1:0", shape=(3,), dtype=int32)
Tensor("Shape_3:0", shape=(1,), dtype=int32)
[0 1 2]


In [6]:
# partial code 2
print(const1.shape[1])
tmp2 = tf.range(0, const1.shape[0]) * const1.shape[1]
print(tmp2)
print(tf.shape(tmp2))
tfutil.print_constant(tmp2)

3
Tensor("mul_1:0", shape=(3,), dtype=int32)
Tensor("Shape_4:0", shape=(1,), dtype=int32)
[0 3 6]


In [7]:
# partial code 3
tmp3 = tmp2 + idx_const2
print(tmp3)
print(tf.shape(tmp3))
tfutil.print_constant(tmp3)

Tensor("add_1:0", shape=(3,), dtype=int32)
Tensor("Shape_5:0", shape=(1,), dtype=int32)
[1 3 8]


In [8]:
params = tf.reshape(x, [-1])  
print(params)
print(tf.shape(params))
tfutil.print_constant(params)

Tensor("Reshape:0", shape=(9,), dtype=int32)
Tensor("Shape_6:0", shape=(1,), dtype=int32)
[1 2 3 4 5 6 7 8 9]


In [9]:
gather_const1 = tf.gather(params,         # flatten input
              idx_flattened)  # use flattened indices
print(gather_const1)
print(tf.shape(gather_const1))
tfutil.print_constant(gather_const1)

Tensor("Gather:0", shape=(3,), dtype=int32)
Tensor("Shape_7:0", shape=(1,), dtype=int32)
[2 4 9]
