In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [0, 1, 2]
const1 = tf.constant(np.array(x))
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(3,), dtype=int64)
Tensor("Shape:0", shape=(1,), dtype=int32)
[0 1 2]


In [3]:
depth = 3
oh_const1 = tf.one_hot(const1, depth)
print(oh_const1)
print(tf.shape(oh_const1))
tfutil.print_operation_value(oh_const1)

Tensor("one_hot:0", shape=(3, 3), dtype=float32)
Tensor("Shape_1:0", shape=(2,), dtype=int32)
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [4]:
x = [0, 2, -1, 1]
const2 = tf.constant(np.array(x))
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(4,), dtype=int64)
Tensor("Shape_2:0", shape=(1,), dtype=int32)
[ 0  2 -1  1]


In [5]:
depth = 3
bm_const2 = tf.one_hot(const2, depth,
    on_value=5.0, off_value=0.0, axis=-1)
print(bm_const2)
print(tf.shape(bm_const2))
tfutil.print_operation_value(bm_const2)

Tensor("one_hot_1:0", shape=(4, 3), dtype=float32)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[ 5.  0.  0.]
 [ 0.  0.  5.]
 [ 0.  0.  0.]
 [ 0.  5.  0.]]


In [6]:
x = [[0, 2], [1, -1]]
const3 = tf.constant(np.array(x)) 
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(2, 2), dtype=int64)
Tensor("Shape_4:0", shape=(2,), dtype=int32)
[[ 0  2]
 [ 1 -1]]


In [7]:
depth = 3
bm_const3 = tf.one_hot(const3, depth, 
    on_value=1.0, off_value=0.0, axis=-1)
print(bm_const3)
print(tf.shape(bm_const3))
tfutil.print_operation_value(bm_const3)

Tensor("one_hot_2:0", shape=(2, 2, 3), dtype=float32)
Tensor("Shape_5:0", shape=(3,), dtype=int32)
[[[ 1.  0.  0.]
  [ 0.  0.  1.]]

 [[ 0.  1.  0.]
  [ 0.  0.  0.]]]
