In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
# [[1, 2, 3], [4, 5, 6]]
const1 = tf.constant(np.array([[1, 2, 3], [4, 5, 6]]), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(2, 3), dtype=int32)
Tensor("Shape:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]]


In [3]:
paddings =  [[0, 0,], [0, 1]]
pad_const1 = tf.pad(const1, paddings, "CONSTANT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("Pad:0", shape=(2, 4), dtype=int32)
Tensor("Shape_1:0", shape=(2,), dtype=int32)
[[1 2 3 0]
 [4 5 6 0]]


In [4]:
paddings =  [[0, 0,], [1, 0]]
pad_const1 = tf.pad(const1, paddings, "CONSTANT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("Pad_1:0", shape=(2, 4), dtype=int32)
Tensor("Shape_2:0", shape=(2,), dtype=int32)
[[0 1 2 3]
 [0 4 5 6]]


In [5]:
paddings =  [[0, 0,], [1, 1]]
pad_const1 = tf.pad(const1, paddings, "CONSTANT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("Pad_2:0", shape=(2, 5), dtype=int32)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[0 1 2 3 0]
 [0 4 5 6 0]]


In [6]:
paddings =  [[0, 1,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "CONSTANT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("Pad_3:0", shape=(3, 3), dtype=int32)
Tensor("Shape_4:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [7]:
paddings =  [[1, 0,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "CONSTANT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("Pad_4:0", shape=(3, 3), dtype=int32)
Tensor("Shape_5:0", shape=(2,), dtype=int32)
[[0 0 0]
 [1 2 3]
 [4 5 6]]


In [8]:
paddings =  [[1, 1,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "CONSTANT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("Pad_5:0", shape=(4, 3), dtype=int32)
Tensor("Shape_6:0", shape=(2,), dtype=int32)
[[0 0 0]
 [1 2 3]
 [4 5 6]
 [0 0 0]]


In [9]:
paddings =  [[1, 1,], [1, 1]]
pad_const1 = tf.pad(const1, paddings, "CONSTANT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("Pad_6:0", shape=(4, 5), dtype=int32)
Tensor("Shape_7:0", shape=(2,), dtype=int32)
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]


In [10]:
# [[1, 2, 3], [4, 5, 6]]
paddings =  [[0, 0,], [0, 1]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad:0", shape=(2, 4), dtype=int32)
Tensor("Shape_8:0", shape=(2,), dtype=int32)
[[1 2 3 2]
 [4 5 6 5]]


In [11]:
paddings =  [[0, 0,], [1, 0]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_1:0", shape=(2, 4), dtype=int32)
Tensor("Shape_9:0", shape=(2,), dtype=int32)
[[2 1 2 3]
 [5 4 5 6]]


In [12]:
paddings =  [[0, 0,], [1, 1]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_2:0", shape=(2, 5), dtype=int32)
Tensor("Shape_10:0", shape=(2,), dtype=int32)
[[2 1 2 3 2]
 [5 4 5 6 5]]


In [13]:
paddings =  [[0, 1,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_3:0", shape=(3, 3), dtype=int32)
Tensor("Shape_11:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [14]:
paddings =  [[1, 0,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_4:0", shape=(3, 3), dtype=int32)
Tensor("Shape_12:0", shape=(2,), dtype=int32)
[[4 5 6]
 [1 2 3]
 [4 5 6]]


In [15]:
paddings =  [[1, 1,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_5:0", shape=(4, 3), dtype=int32)
Tensor("Shape_13:0", shape=(2,), dtype=int32)
[[4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]


In [16]:
paddings =  [[1, 1,], [1, 1]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_6:0", shape=(4, 5), dtype=int32)
Tensor("Shape_14:0", shape=(2,), dtype=int32)
[[5 4 5 6 5]
 [2 1 2 3 2]
 [5 4 5 6 5]
 [2 1 2 3 2]]


In [17]:
paddings =  [[1, 1,], [2, 2]]
pad_const1 = tf.pad(const1, paddings, "REFLECT")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_7:0", shape=(4, 7), dtype=int32)
Tensor("Shape_15:0", shape=(2,), dtype=int32)
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]]


In [18]:
# [[1, 2, 3], [4, 5, 6]]
paddings =  [[0, 0,], [0, 1]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_8:0", shape=(2, 4), dtype=int32)
Tensor("Shape_16:0", shape=(2,), dtype=int32)
[[1 2 3 3]
 [4 5 6 6]]


In [19]:
paddings =  [[0, 0,], [1, 0]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_9:0", shape=(2, 4), dtype=int32)
Tensor("Shape_17:0", shape=(2,), dtype=int32)
[[1 1 2 3]
 [4 4 5 6]]


In [20]:
paddings =  [[0, 0,], [1, 1]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_10:0", shape=(2, 5), dtype=int32)
Tensor("Shape_18:0", shape=(2,), dtype=int32)
[[1 1 2 3 3]
 [4 4 5 6 6]]


In [21]:
paddings =  [[0, 1,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_11:0", shape=(3, 3), dtype=int32)
Tensor("Shape_19:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [22]:
paddings =  [[1, 0,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_12:0", shape=(3, 3), dtype=int32)
Tensor("Shape_20:0", shape=(2,), dtype=int32)
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [23]:
paddings =  [[1, 1,], [0, 0]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_13:0", shape=(4, 3), dtype=int32)
Tensor("Shape_21:0", shape=(2,), dtype=int32)
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [24]:
paddings =  [[1, 1,], [1, 1]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_14:0", shape=(4, 5), dtype=int32)
Tensor("Shape_22:0", shape=(2,), dtype=int32)
[[1 1 2 3 3]
 [1 1 2 3 3]
 [4 4 5 6 6]
 [4 4 5 6 6]]


In [25]:
paddings =  [[1, 1,], [2, 2]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_15:0", shape=(4, 7), dtype=int32)
Tensor("Shape_23:0", shape=(2,), dtype=int32)
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]]


In [26]:
paddings =  [[1, 1,], [3, 3]]
pad_const1 = tf.pad(const1, paddings, "SYMMETRIC")
print(pad_const1)
print(tf.shape(pad_const1))
tfutil.print_operation_value(pad_const1)

Tensor("MirrorPad_16:0", shape=(4, 9), dtype=int32)
Tensor("Shape_24:0", shape=(2,), dtype=int32)
[[3 2 1 1 2 3 3 2 1]
 [3 2 1 1 2 3 3 2 1]
 [6 5 4 4 5 6 6 5 4]
 [6 5 4 4 5 6 6 5 4]]
