In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [[[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],
        [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]]]

const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(1, 2, 3, 4), dtype=int32)
Tensor("Shape:0", shape=(4,), dtype=int32)
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


In [3]:
dims = [3]
dims_const1 = tf.reverse(const1, dims)
print(dims_const1)
print(tf.shape(dims_const1))
tfutil.print_operation_value(dims_const1)

Tensor("ReverseV2:0", shape=(1, 2, 3, 4), dtype=int32)
Tensor("Shape_1:0", shape=(4,), dtype=int32)
[[[[ 3  2  1  0]
   [ 7  6  5  4]
   [11 10  9  8]]

  [[15 14 13 12]
   [19 18 17 16]
   [23 22 21 20]]]]


In [4]:
dims = [1] 
dims_const1 = tf.reverse(const1, dims)
print(dims_const1)
print(tf.shape(dims_const1))
tfutil.print_operation_value(dims_const1)

Tensor("ReverseV2_1:0", shape=(1, 2, 3, 4), dtype=int32)
Tensor("Shape_2:0", shape=(4,), dtype=int32)
[[[[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]

  [[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]]]


In [5]:
 dims = [2] 
dims_const1 = tf.reverse(const1, dims)
print(dims_const1)
print(tf.shape(dims_const1))
tfutil.print_operation_value(dims_const1)

Tensor("ReverseV2_2:0", shape=(1, 2, 3, 4), dtype=int32)
Tensor("Shape_3:0", shape=(4,), dtype=int32)
[[[[ 8  9 10 11]
   [ 4  5  6  7]
   [ 0  1  2  3]]

  [[20 21 22 23]
   [16 17 18 19]
   [12 13 14 15]]]]
