In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [[1, 2, 3, 4, 0, 0, 0],
     [1, 2, 3, 0, 0, 0, 0],
     [1, 2, 3, 4, 5, 6, 7]]
const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(3, 7), dtype=int32)
Tensor("Shape:0", shape=(2,), dtype=int32)
[[1 2 3 4 0 0 0]
 [1 2 3 0 0 0 0]
 [1 2 3 4 5 6 7]]


In [3]:
seq_lens = [4, 3, 7]
rs_const1 = tf.reverse_sequence(const1, seq_lens, seq_dim=1, batch_dim=0)
print(rs_const1)
print(tf.shape(rs_const1))
tfutil.print_operation_value(rs_const1)

Tensor("ReverseSequence:0", shape=(3, 7), dtype=int32)
Tensor("Shape_1:0", shape=(2,), dtype=int32)
[[4 3 2 1 0 0 0]
 [3 2 1 0 0 0 0]
 [7 6 5 4 3 2 1]]


In [4]:
x = [[[1, 2, 3, 4, 0, 0, 0], [1, 0, 2, 0, 0, 0, 0]],
     [[1, 2, 3, 4, 5, 0, 0], [0, 2, 1, 4, 0, 0, 0]],
     [[1, 2, 3, 4, 5, 6 ,7], [1, 2, 3, 4, 0, 6, 0]]]
const2 = tf.constant(np.array(x), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(3, 2, 7), dtype=int32)
Tensor("Shape_2:0", shape=(3,), dtype=int32)
[[[1 2 3 4 0 0 0]
  [1 0 2 0 0 0 0]]

 [[1 2 3 4 5 0 0]
  [0 2 1 4 0 0 0]]

 [[1 2 3 4 5 6 7]
  [1 2 3 4 0 6 0]]]


In [5]:
seq_lens = [4, 3, 5]
rs_const2 = tf.reverse_sequence(const2, seq_lens, seq_dim=2, batch_dim=0)
print(rs_const2)
print(tf.shape(rs_const2))
tfutil.print_operation_value(rs_const2)

Tensor("ReverseSequence_1:0", shape=(3, 2, 7), dtype=int32)
Tensor("Shape_3:0", shape=(3,), dtype=int32)
[[[4 3 2 1 0 0 0]
  [0 2 0 1 0 0 0]]

 [[3 2 1 4 5 0 0]
  [1 2 0 4 0 0 0]]

 [[5 4 3 2 1 6 7]
  [0 4 3 2 1 6 0]]]


In [6]:
seq_lens = [4, 3]
rs_const2 = tf.reverse_sequence(const2, seq_lens, seq_dim=2, batch_dim=1)
print(rs_const2)
print(tf.shape(rs_const2))
tfutil.print_operation_value(rs_const2)

Tensor("ReverseSequence_2:0", shape=(3, 2, 7), dtype=int32)
Tensor("Shape_4:0", shape=(3,), dtype=int32)
[[[4 3 2 1 0 0 0]
  [2 0 1 0 0 0 0]]

 [[4 3 2 1 5 0 0]
  [1 2 0 4 0 0 0]]

 [[4 3 2 1 5 6 7]
  [3 2 1 4 0 6 0]]]
