In [1]:
import tensorflow as tf
import tfutil

# [1, 2, 3, 4, 5, 6, 7, 8, 9]
const1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(9,), dtype=int32)
Tensor("Shape:0", shape=(1,), dtype=int32)
[1 2 3 4 5 6 7 8 9]


In [2]:
sl_const1 = tf.slice(const1, [2], [3])
print(sl_const1)
print(tf.shape(sl_const1))
tfutil.print_operation_value(sl_const1)

Tensor("Slice:0", shape=(3,), dtype=int32)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[3 4 5]


In [3]:
# [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19,20]]
const2 = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19,20]])
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(2, 10), dtype=int32)
Tensor("Shape_2:0", shape=(2,), dtype=int32)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [4]:
sl_const2 = tf.slice(const2, [0, 1], [1, 3])
print(sl_const2)
print(tf.shape(sl_const2))
tfutil.print_operation_value(sl_const2)

Tensor("Slice_1:0", shape=(1, 3), dtype=int32)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[2 3 4]]


In [5]:
sl_const2 = tf.slice(const2, [0, 2], [1, 3])
print(sl_const2)
print(tf.shape(sl_const2))
tfutil.print_operation_value(sl_const2)

Tensor("Slice_2:0", shape=(1, 3), dtype=int32)
Tensor("Shape_4:0", shape=(2,), dtype=int32)
[[3 4 5]]


In [6]:
sl_const2 = tf.slice(const2, [1, 1], [1, 3])
print(sl_const2)
print(tf.shape(sl_const2))
tfutil.print_operation_value(sl_const2)

Tensor("Slice_3:0", shape=(1, 3), dtype=int32)
Tensor("Shape_5:0", shape=(2,), dtype=int32)
[[12 13 14]]


In [7]:
sl_const2 = tf.slice(const2, [1, 2], [1, 3])
print(sl_const2)
print(tf.shape(sl_const2))
tfutil.print_operation_value(sl_const2)

Tensor("Slice_4:0", shape=(1, 3), dtype=int32)
Tensor("Shape_6:0", shape=(2,), dtype=int32)
[[13 14 15]]


In [8]:
# [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
const3 = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(3, 2, 3), dtype=int32)
Tensor("Shape_7:0", shape=(3,), dtype=int32)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [9]:
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_5:0", shape=(1, 1, 1), dtype=int32)
Tensor("Shape_8:0", shape=(3,), dtype=int32)
[[[1]]]


In [10]:
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_6:0", shape=(1, 1, 2), dtype=int32)
Tensor("Shape_9:0", shape=(3,), dtype=int32)
[[[1 2]]]


In [11]:
sl_const3 = tf.slice(const3, [0, 1, 0], [1, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_7:0", shape=(1, 1, 1), dtype=int32)
Tensor("Shape_10:0", shape=(3,), dtype=int32)
[[[4]]]


In [12]:
sl_const3 = tf.slice(const3, [0, 1, 0], [1, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_8:0", shape=(1, 1, 2), dtype=int32)
Tensor("Shape_11:0", shape=(3,), dtype=int32)
[[[4 5]]]


In [13]:
sl_const3 = tf.slice(const3, [1, 0, 0], [1, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_9:0", shape=(1, 1, 1), dtype=int32)
Tensor("Shape_12:0", shape=(3,), dtype=int32)
[[[7]]]


In [14]:
sl_const3 = tf.slice(const3, [1, 0, 0], [1, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_10:0", shape=(1, 1, 2), dtype=int32)
Tensor("Shape_13:0", shape=(3,), dtype=int32)
[[[7 8]]]


In [15]:
sl_const3 = tf.slice(const3, [1, 1, 0], [1, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_11:0", shape=(1, 1, 1), dtype=int32)
Tensor("Shape_14:0", shape=(3,), dtype=int32)
[[[10]]]


In [16]:
sl_const3 = tf.slice(const3, [1, 1, 0], [1, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_12:0", shape=(1, 1, 2), dtype=int32)
Tensor("Shape_15:0", shape=(3,), dtype=int32)
[[[10 11]]]


In [17]:
sl_const3 = tf.slice(const3, [2, 0, 0], [1, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_13:0", shape=(1, 1, 1), dtype=int32)
Tensor("Shape_16:0", shape=(3,), dtype=int32)
[[[13]]]


In [18]:
sl_const3 = tf.slice(const3, [2, 0, 0], [1, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_14:0", shape=(1, 1, 2), dtype=int32)
Tensor("Shape_17:0", shape=(3,), dtype=int32)
[[[13 14]]]


In [19]:
sl_const3 = tf.slice(const3, [2, 1, 0], [1, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_15:0", shape=(1, 1, 1), dtype=int32)
Tensor("Shape_18:0", shape=(3,), dtype=int32)
[[[16]]]


In [20]:
sl_const3 = tf.slice(const3, [2, 1, 0], [1, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_16:0", shape=(1, 1, 2), dtype=int32)
Tensor("Shape_19:0", shape=(3,), dtype=int32)
[[[16 17]]]


In [21]:
# [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_17:0", shape=(1, 1, 1), dtype=int32)
Tensor("Shape_20:0", shape=(3,), dtype=int32)
[[[1]]]


In [22]:
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_18:0", shape=(1, 1, 2), dtype=int32)
Tensor("Shape_21:0", shape=(3,), dtype=int32)
[[[1 2]]]


In [23]:
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 1, 3])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_19:0", shape=(1, 1, 3), dtype=int32)
Tensor("Shape_22:0", shape=(3,), dtype=int32)
[[[1 2 3]]]


In [24]:
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 2, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_20:0", shape=(1, 2, 1), dtype=int32)
Tensor("Shape_23:0", shape=(3,), dtype=int32)
[[[1]
  [4]]]


In [25]:
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 2, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_21:0", shape=(1, 2, 2), dtype=int32)
Tensor("Shape_24:0", shape=(3,), dtype=int32)
[[[1 2]
  [4 5]]]


In [26]:
sl_const3 = tf.slice(const3, [0, 0, 0], [1, 2, 3])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_22:0", shape=(1, 2, 3), dtype=int32)
Tensor("Shape_25:0", shape=(3,), dtype=int32)
[[[1 2 3]
  [4 5 6]]]


In [27]:
sl_const3 = tf.slice(const3, [0, 0, 0], [3, 1, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_23:0", shape=(3, 1, 1), dtype=int32)
Tensor("Shape_26:0", shape=(3,), dtype=int32)
[[[ 1]]

 [[ 7]]

 [[13]]]


In [28]:
sl_const3 = tf.slice(const3, [0, 0, 0], [3, 2, 1])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_24:0", shape=(3, 2, 1), dtype=int32)
Tensor("Shape_27:0", shape=(3,), dtype=int32)
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]

 [[13]
  [16]]]


In [29]:
sl_const3 = tf.slice(const3, [0, 0, 0], [3, 1, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_25:0", shape=(3, 1, 2), dtype=int32)
Tensor("Shape_28:0", shape=(3,), dtype=int32)
[[[ 1  2]]

 [[ 7  8]]

 [[13 14]]]


In [30]:
sl_const3 = tf.slice(const3, [0, 0, 0], [3, 2, 2])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_26:0", shape=(3, 2, 2), dtype=int32)
Tensor("Shape_29:0", shape=(3,), dtype=int32)
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]


In [31]:
sl_const3 = tf.slice(const3, [0, 0, 0], [3, 1, 3])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_27:0", shape=(3, 1, 3), dtype=int32)
Tensor("Shape_30:0", shape=(3,), dtype=int32)
[[[ 1  2  3]]

 [[ 7  8  9]]

 [[13 14 15]]]


In [32]:
sl_const3 = tf.slice(const3, [0, 0, 0], [3, 2, 3])
print(sl_const3)
print(tf.shape(sl_const3))
tfutil.print_operation_value(sl_const3)

Tensor("Slice_28:0", shape=(3, 2, 3), dtype=int32)
Tensor("Shape_31:0", shape=(3,), dtype=int32)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
