In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [[[[1], [2]], [[3], [4]]]]
const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [3]:
# return: [batch*block_size*block_size, height_pad/block_size, width_pad/block_size, depth]
# paddings = [[pad_top, pad_bottom], [pad_left, pad_right]]
# height_pad = pad_top + height + pad_bottom
# width_pad = pad_left + width + pad_right
# blocksize = Both height_pad and width_pad must be divisible by block_size.
paddings = [[0, 0],[0, 0]]
blocksize = 1
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_1:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [4]:
paddings = [[0, 0],[0, 1]]
blocksize = 1
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_1:0", shape=(1, 2, 3, 1), dtype=int32)
Tensor("Shape_2:0", shape=(4,), dtype=int32)
[[[[1]
   [2]
   [0]]

  [[3]
   [4]
   [0]]]]


In [5]:
paddings = [[0, 0],[1, 1]]
blocksize = 1
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_2:0", shape=(1, 2, 4, 1), dtype=int32)
Tensor("Shape_3:0", shape=(4,), dtype=int32)
[[[[0]
   [1]
   [2]
   [0]]

  [[0]
   [3]
   [4]
   [0]]]]


In [6]:
paddings = [[0, 1],[1, 1]]
blocksize = 1
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_3:0", shape=(1, 3, 4, 1), dtype=int32)
Tensor("Shape_4:0", shape=(4,), dtype=int32)
[[[[0]
   [1]
   [2]
   [0]]

  [[0]
   [3]
   [4]
   [0]]

  [[0]
   [0]
   [0]
   [0]]]]


In [7]:
paddings = [[1, 1],[1, 1]]
blocksize = 1
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_4:0", shape=(1, 4, 4, 1), dtype=int32)
Tensor("Shape_5:0", shape=(4,), dtype=int32)
[[[[0]
   [0]
   [0]
   [0]]

  [[0]
   [1]
   [2]
   [0]]

  [[0]
   [3]
   [4]
   [0]]

  [[0]
   [0]
   [0]
   [0]]]]


In [8]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_5:0", shape=(4, 1, 1, 1), dtype=int32)
Tensor("Shape_6:0", shape=(4,), dtype=int32)
[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]]


In [9]:
# [batch*block_size*block_size, height_pad/block_size, width_pad/block_size, depth]
# blocksize = Both height_pad and width_pad must be divisible by block_size.
paddings = [[0, 0],[1, 1]]
blocksize = 2
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_6:0", shape=(4, 1, 2, 1), dtype=int32)
Tensor("Shape_7:0", shape=(4,), dtype=int32)
[[[[0]
   [2]]]


 [[[1]
   [0]]]


 [[[0]
   [4]]]


 [[[3]
   [0]]]]


In [10]:
# [batch*block_size*block_size, height_pad/block_size, width_pad/block_size, depth]
# blocksize = Both height_pad and width_pad must be divisible by block_size.
paddings = [[1, 1],[1, 1]]
blocksize = 2
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_7:0", shape=(4, 2, 2, 1), dtype=int32)
Tensor("Shape_8:0", shape=(4,), dtype=int32)
[[[[0]
   [0]]

  [[0]
   [4]]]


 [[[0]
   [0]]

  [[3]
   [0]]]


 [[[0]
   [2]]

  [[0]
   [0]]]


 [[[1]
   [0]]

  [[0]
   [0]]]]


In [11]:
x = [[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]]
const2 = tf.constant(np.array(x), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(1, 2, 2, 3), dtype=int32)
Tensor("Shape_9:0", shape=(4,), dtype=int32)
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [12]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const2 = tf.space_to_batch(const2, paddings, blocksize)
print(stb_const2)
print(tf.shape(stb_const2))
tfutil.print_operation_value(stb_const2)

Tensor("SpaceToBatchND_8:0", shape=(4, 1, 1, 3), dtype=int32)
Tensor("Shape_10:0", shape=(4,), dtype=int32)
[[[[ 1  2  3]]]


 [[[ 4  5  6]]]


 [[[ 7  8  9]]]


 [[[10 11 12]]]]


In [13]:
x = [[[[1], [2], [3], [4]], [[5], [6], [7], [8]], [[9], [10], [11], [12]], [[13], [14], [15], [16]]]]
const3 = tf.constant(np.array(x), dtype=tf.int32)
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(1, 4, 4, 1), dtype=int32)
Tensor("Shape_11:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [11]
   [12]]

  [[13]
   [14]
   [15]
   [16]]]]


In [14]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const3 = tf.space_to_batch(const3, paddings, blocksize)
print(stb_const3)
print(tf.shape(stb_const3))
tfutil.print_operation_value(stb_const3)

Tensor("SpaceToBatchND_9:0", shape=(4, 2, 2, 1), dtype=int32)
Tensor("Shape_12:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 3]]

  [[ 9]
   [11]]]


 [[[ 2]
   [ 4]]

  [[10]
   [12]]]


 [[[ 5]
   [ 7]]

  [[13]
   [15]]]


 [[[ 6]
   [ 8]]

  [[14]
   [16]]]]


In [15]:
x = [[[[1], [2], [3], [4]], [[5], [6], [7], [8]]], [[[9], [10], [11], [12]], [[13], [14], [15], [16]]]]
const4 = tf.constant(np.array(x), dtype=tf.int32)
print(const4)
print(tf.shape(const4))
tfutil.print_constant(const4)

Tensor("Const_3:0", shape=(2, 2, 4, 1), dtype=int32)
Tensor("Shape_13:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]]]


 [[[ 9]
   [10]
   [11]
   [12]]

  [[13]
   [14]
   [15]
   [16]]]]


In [16]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const4 = tf.space_to_batch(const4, paddings, blocksize)
print(stb_const4)
print(tf.shape(stb_const4))
tfutil.print_operation_value(stb_const4)

Tensor("SpaceToBatchND_10:0", shape=(8, 1, 2, 1), dtype=int32)
Tensor("Shape_14:0", shape=(4,), dtype=int32)
[[[[ 1]
   [ 3]]]


 [[[ 9]
   [11]]]


 [[[ 2]
   [ 4]]]


 [[[10]
   [12]]]


 [[[ 5]
   [ 7]]]


 [[[13]
   [15]]]


 [[[ 6]
   [ 8]]]


 [[[14]
   [16]]]]
