In [15]:
import tensorflow as tf
import numpy as np
import tfutil


images = [[[[1], [2]], [[3], [4]]]]

const1 = tf.constant(np.array(images), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const_5:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_8:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [16]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const1 = tf.space_to_batch(const1, paddings, blocksize)
print(stb_const1)
print(tf.shape(stb_const1))
tfutil.print_operation_value(stb_const1)

Tensor("SpaceToBatchND_9:0", shape=(4, 1, 1, 1), dtype=int32)
Tensor("Shape_9:0", shape=(4,), dtype=int32)
[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]]


In [17]:
x = [[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]]
const2 = tf.constant(np.array(images), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_6:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_10:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [18]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const2 = tf.space_to_batch(const2, paddings, blocksize)
print(stb_const2)
print(tf.shape(stb_const2))
tfutil.print_operation_value(stb_const2)

Tensor("SpaceToBatchND_10:0", shape=(4, 1, 1, 1), dtype=int32)
Tensor("Shape_11:0", shape=(4,), dtype=int32)
[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]]


In [19]:
x = [[[[1], [2], [3], [4]], [[5], [6], [7], [8]], [[9], [10], [11], [12]], [[13], [14], [15], [16]]]]
const3 = tf.constant(np.array(images), dtype=tf.int32)
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_7:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_12:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [20]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const3 = tf.space_to_batch(const3, paddings, blocksize)
print(stb_const3)
print(tf.shape(stb_const3))
tfutil.print_operation_value(stb_const3)


Tensor("SpaceToBatchND_11:0", shape=(4, 1, 1, 1), dtype=int32)
Tensor("Shape_13:0", shape=(4,), dtype=int32)
[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]]


In [21]:
x = [[[[1], [2], [3], [4]], [[5], [6], [7], [8]]], [[[9], [10], [11], [12]], [[13], [14], [15], [16]]]]
const4 = tf.constant(np.array(images), dtype=tf.int32)
print(const4)
print(tf.shape(const4))
tfutil.print_constant(const4)


Tensor("Const_8:0", shape=(1, 2, 2, 1), dtype=int32)
Tensor("Shape_14:0", shape=(4,), dtype=int32)
[[[[1]
   [2]]

  [[3]
   [4]]]]


In [22]:
paddings = [[0, 0],[0, 0]]
blocksize = 2
stb_const4 = tf.space_to_batch(const4, paddings, blocksize)
print(stb_const4)
print(tf.shape(stb_const4))
tfutil.print_operation_value(stb_const4)


Tensor("SpaceToBatchND_12:0", shape=(4, 1, 1, 1), dtype=int32)
Tensor("Shape_15:0", shape=(4,), dtype=int32)
[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]]
