In [1]:
import tensorflow as tf
import numpy as np
import tfutil


# [1, 2, 3, 4, 5, 6, 7, 8, 9]
const1 = tf.constant(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(10,), dtype=int32)
Tensor("Shape:0", shape=(1,), dtype=int32)
[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
sp1_const1, sp2_const1 = tf.split(const1, 2, 0)
print(sp1_const1)
print(tf.shape(sp1_const1))
tfutil.print_operation_value(sp1_const1)

Tensor("split:0", shape=(5,), dtype=int32)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[1 2 3 4 5]


In [3]:
print(sp2_const1)
print(tf.shape(sp2_const1))
tfutil.print_operation_value(sp2_const1)

Tensor("split:1", shape=(5,), dtype=int32)
Tensor("Shape_2:0", shape=(1,), dtype=int32)
[ 6  7  8  9 10]


In [4]:
# [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
const2 = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_2:0", shape=(5, 4), dtype=int32)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [5]:
sp1_const2, sp2_const2 = tf.split(const2, 2, 1)
print(sp1_const2)
print(tf.shape(sp1_const2))
tfutil.print_operation_value(sp1_const2)

Tensor("split_1:0", shape=(5, 2), dtype=int32)
Tensor("Shape_4:0", shape=(2,), dtype=int32)
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]


In [6]:
print(sp2_const2)
print(tf.shape(sp2_const2))
tfutil.print_operation_value(sp2_const2)

Tensor("split_1:1", shape=(5, 2), dtype=int32)
Tensor("Shape_5:0", shape=(2,), dtype=int32)
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]]


In [7]:
# [5, 30]
var1 = tf.Variable(tf.random_normal([5, 30]))
print(var1)
print(tf.shape(var1))

<tf.Variable 'Variable:0' shape=(5, 30) dtype=float32_ref>
Tensor("Shape_6:0", shape=(2,), dtype=int32)


In [8]:
sp1_var1, sp2_var1, sp3_var1 = tf.split(var1, 3, 1)
print(sp1_var1)
print(tf.shape(sp1_var1))

Tensor("split_2:0", shape=(5, 10), dtype=float32)
Tensor("Shape_7:0", shape=(2,), dtype=int32)


In [9]:
print(sp2_var1)
print(tf.shape(sp2_var1))

Tensor("split_2:1", shape=(5, 10), dtype=float32)
Tensor("Shape_8:0", shape=(2,), dtype=int32)


In [10]:
print(sp3_var1)
print(tf.shape(sp3_var1))

Tensor("split_2:2", shape=(5, 10), dtype=float32)
Tensor("Shape_9:0", shape=(2,), dtype=int32)
