In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
const1 = tf.constant(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(10,), dtype=int32)
Tensor("Shape:0", shape=(1,), dtype=int32)
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
ti_const1 = tf.tile(const1, [1])
print(ti_const1)
print(tf.shape(ti_const1))
tfutil.print_operation_value(ti_const1)

Tensor("Tile:0", shape=(10,), dtype=int32)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
ti_const1 = tf.tile(const1, [2])
print(ti_const1)
print(tf.shape(ti_const1))
tfutil.print_operation_value(ti_const1)

Tensor("Tile_1:0", shape=(20,), dtype=int32)
Tensor("Shape_2:0", shape=(1,), dtype=int32)
[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


In [5]:
ti_const1 = tf.tile(const1, [3])
print(ti_const1)
print(tf.shape(ti_const1))
tfutil.print_operation_value(ti_const1)

Tensor("Tile_2:0", shape=(30,), dtype=int32)
Tensor("Shape_3:0", shape=(1,), dtype=int32)
[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5
  6  7  8  9 10]
