In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
'''
A=[2,3,4] matrix, using perm(1,0,2) will get B=[3,2,4]

Index = (0,1,2)
A     = [2,3,4]
Perm  = (1,0,2)
B     = (3,2,4)  --> Perm 1 from Index 1 (3), Perm 0 from Index 0 (2), Perm 2 from Index 2 (4) --> so get (3,2,4
'''

'\nA=[2,3,4] matrix, using perm(1,0,2) will get B=[3,2,4]\n\nIndex = (0,1,2)\nA     = [2,3,4]\nPerm  = (1,0,2)\nB     = (3,2,4)  --> Perm 1 from Index 1 (3), Perm 0 from Index 0 (2), Perm 2 from Index 2 (4) --> so get (3,2,4\n'

In [3]:
x = [[1, 2, 3, 4, 5, 6]]

const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(1, 6), dtype=int32)
Tensor("Shape:0", shape=(2,), dtype=int32)
[[1 2 3 4 5 6]]


In [4]:
perm = [1, 0]
trans_const1 = tf.transpose(const1, perm)
print(trans_const1)
print(tf.shape(trans_const1))
tfutil.print_operation_value(trans_const1)

Tensor("transpose:0", shape=(6, 1), dtype=int32)
Tensor("Shape_1:0", shape=(2,), dtype=int32)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
perm = [0, 1]
trans_const1 = tf.transpose(const1, perm)
print(trans_const1)
print(tf.shape(trans_const1))
tfutil.print_operation_value(trans_const1)

Tensor("transpose_1:0", shape=(1, 6), dtype=int32)
Tensor("Shape_2:0", shape=(2,), dtype=int32)
[[1 2 3 4 5 6]]


In [6]:
x = [[1, 2, 3], [4, 5, 6]]
const2 = tf.constant(np.array(x), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(2, 3), dtype=int32)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]]


In [7]:
perm = [1, 0] 
trans_const2 = tf.transpose(const2, perm)
print(trans_const2)
print(tf.shape(trans_const2))
tfutil.print_operation_value(trans_const2)

Tensor("transpose_2:0", shape=(3, 2), dtype=int32)
Tensor("Shape_4:0", shape=(2,), dtype=int32)
[[1 4]
 [2 5]
 [3 6]]


In [8]:
perm = [0, 1] 
trans_const2 = tf.transpose(const2, perm)
print(trans_const2)
print(tf.shape(trans_const2))
tfutil.print_operation_value(trans_const2)

Tensor("transpose_3:0", shape=(2, 3), dtype=int32)
Tensor("Shape_5:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]]


In [9]:
x = [[[ 1,  2,  3],
      [ 4,  5,  6]],
     [[ 7,  8,  9],
      [10, 11, 12]]]
const3 = tf.constant(np.array(x), dtype=tf.int32)
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(2, 2, 3), dtype=int32)
Tensor("Shape_6:0", shape=(3,), dtype=int32)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
perm = [1, 0, 2] 
trans_const3 = tf.transpose(const3, perm)
print(trans_const3)
print(tf.shape(trans_const3))
tfutil.print_operation_value(trans_const3)

Tensor("transpose_4:0", shape=(2, 2, 3), dtype=int32)
Tensor("Shape_7:0", shape=(3,), dtype=int32)
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [11]:
perm = [2, 0, 1] 
trans_const3 = tf.transpose(const3, perm)
print(trans_const3)
print(tf.shape(trans_const3))
tfutil.print_operation_value(trans_const3)

Tensor("transpose_5:0", shape=(3, 2, 2), dtype=int32)
Tensor("Shape_8:0", shape=(3,), dtype=int32)
[[[ 1  4]
  [ 7 10]]

 [[ 2  5]
  [ 8 11]]

 [[ 3  6]
  [ 9 12]]]


In [12]:
perm = [2, 1, 0] 
trans_const3 = tf.transpose(const3, perm)
print(trans_const3)
print(tf.shape(trans_const3))
tfutil.print_operation_value(trans_const3)

Tensor("transpose_6:0", shape=(3, 2, 2), dtype=int32)
Tensor("Shape_9:0", shape=(3,), dtype=int32)
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [13]:
perm = [1, 2, 0] 
trans_const3 = tf.transpose(const3, perm)
print(trans_const3)
print(tf.shape(trans_const3))
tfutil.print_operation_value(trans_const3)

Tensor("transpose_7:0", shape=(2, 3, 2), dtype=int32)
Tensor("Shape_10:0", shape=(3,), dtype=int32)
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [14]:
perm = [0, 2, 1] 
trans_const3 = tf.transpose(const3, perm)
print(trans_const3)
print(tf.shape(trans_const3))
tfutil.print_operation_value(trans_const3)

Tensor("transpose_8:0", shape=(2, 3, 2), dtype=int32)
Tensor("Shape_11:0", shape=(3,), dtype=int32)
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [15]:
perm = [0, 1, 2] 
trans_const3 = tf.transpose(const3, perm)
print(trans_const3)
print(tf.shape(trans_const3))
tfutil.print_operation_value(trans_const3)

Tensor("transpose_9:0", shape=(2, 2, 3), dtype=int32)
Tensor("Shape_12:0", shape=(3,), dtype=int32)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
