In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
x = [1, 1, 2, 4, 4, 4, 7, 8, 8]

const1 = tf.constant(np.array(x), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(9,), dtype=int32)
Tensor("Shape:0", shape=(1,), dtype=int32)
[1 1 2 4 4 4 7 8 8]


In [3]:
y, idx, count = tf.unique_with_counts(const1)
print(y)
print(tf.shape(y))
tfutil.print_constant(y)

Tensor("UniqueWithCounts:0", shape=(?,), dtype=int32)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[1 2 4 7 8]


In [4]:
print(idx)
print(tf.shape(idx))
tfutil.print_constant(idx)

Tensor("UniqueWithCounts:1", shape=(9,), dtype=int32)
Tensor("Shape_2:0", shape=(1,), dtype=int32)
[0 0 1 2 2 2 3 4 4]


In [5]:
print(count)
print(tf.shape(count))
tfutil.print_constant(count)

Tensor("UniqueWithCounts:2", shape=(?,), dtype=int32)
Tensor("Shape_3:0", shape=(1,), dtype=int32)
[2 1 3 1 2]
