In [1]:
import tensorflow as tf
import numpy as np
import tfutil

In [2]:
const1 = tf.constant(np.array([1, 2, 3]), dtype=tf.int32)
print(const1)
print(tf.shape(const1))
tfutil.print_constant(const1)

Tensor("Const:0", shape=(3,), dtype=int32)
Tensor("Shape:0", shape=(1,), dtype=int32)
[1 2 3]


In [3]:
const2 = tf.constant(np.array([4, 5, 6]), dtype=tf.int32)
print(const2)
print(tf.shape(const2))
tfutil.print_constant(const2)

Tensor("Const_1:0", shape=(3,), dtype=int32)
Tensor("Shape_1:0", shape=(1,), dtype=int32)
[4 5 6]


In [4]:
const3 = tf.constant(np.array([7, 8, 9]), dtype=tf.int32)
print(const3)
print(tf.shape(const3))
tfutil.print_constant(const3)

Tensor("Const_2:0", shape=(3,), dtype=int32)
Tensor("Shape_2:0", shape=(1,), dtype=int32)
[7 8 9]


In [5]:
pack_const1 = tf.stack([const1, const2, const3])
print(pack_const1)
print(tf.shape(pack_const1))
tfutil.print_operation_value(pack_const1)

Tensor("stack:0", shape=(3, 3), dtype=int32)
Tensor("Shape_3:0", shape=(2,), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
up_const1, up_const2, up_const3 = tf.unstack(pack_const1)
print(up_const1)
print(tf.shape(up_const1))
tfutil.print_constant(up_const1)

Tensor("unstack:0", shape=(3,), dtype=int32)
Tensor("Shape_4:0", shape=(1,), dtype=int32)
[1 2 3]


In [7]:
print(up_const2)
print(tf.shape(up_const2))
tfutil.print_constant(up_const2)

Tensor("unstack:1", shape=(3,), dtype=int32)
Tensor("Shape_5:0", shape=(1,), dtype=int32)
[4 5 6]


In [8]:
print(up_const3)
print(tf.shape(up_const3))
tfutil.print_constant(up_const3)

Tensor("unstack:2", shape=(3,), dtype=int32)
Tensor("Shape_6:0", shape=(1,), dtype=int32)
[7 8 9]


In [9]:
pack_const1 = tf.stack([const1, const2, const3], axis=1)
print(pack_const1)
print(tf.shape(pack_const1))
tfutil.print_operation_value(pack_const1)

Tensor("stack_1:0", shape=(3, 3), dtype=int32)
Tensor("Shape_7:0", shape=(2,), dtype=int32)
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
up_const1, up_const2, up_const3 = tf.unstack(pack_const1)
print(up_const1)
print(tf.shape(up_const1))
tfutil.print_constant(up_const1)

Tensor("unstack_1:0", shape=(3,), dtype=int32)
Tensor("Shape_8:0", shape=(1,), dtype=int32)
[1 4 7]


In [11]:
print(up_const2)
print(tf.shape(up_const2))
tfutil.print_constant(up_const2)

Tensor("unstack_1:1", shape=(3,), dtype=int32)
Tensor("Shape_9:0", shape=(1,), dtype=int32)
[2 5 8]


In [12]:
print(up_const3)
print(tf.shape(up_const3))
tfutil.print_constant(up_const3)

Tensor("unstack_1:2", shape=(3,), dtype=int32)
Tensor("Shape_10:0", shape=(1,), dtype=int32)
[3 6 9]
